# 百度链接自动推送
name: 百度链接自动推送

# 触发条件（重点：加了手动触发 + 代码更新触发）
on:
  schedule:
    # 每 10 分钟执行一次 (一天共执行 144 次)
    - cron: '*/10 * * * *'
  workflow_dispatch: # 保留此项以便手动触发
  # 代码推送到main分支自动触发
  push:
    branches:
      - main
    paths:
      - urls.txt

# 自动化任务
jobs:
  push-to-baidu:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 推送百度收录
        run: |
          curl -H 'Content-Type:text/plain' --data-binary @urls.txt "http://data.zz.baidu.com/urls?site=https://weiqinzhang.top&token=FUY3EZ2ObHAeUSVM"
